### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [nancylee713/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The four methods I chose for **Class #1** represent behaviors or actions.
- [x] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [ ] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The four methods I chose for **Class #2** represent behaviors or actions.
- [x] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [x] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [ ] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message.

Good job on the assessment Nancy. We do want you to make some changes around the OOP portion of the assessment. Remember that the class is the blueprint to make many different objects that share attributes and methods, but will probably have different values for those attributes. We wouldn't want a class named `School A` or `School B`. We would want a class named `School`. This class could then make instances of itself like `Cherry Creek High School` or `Denver Academy`. I think what happened is that you misread the instructions here. We wanted you to think of things within a school that could represent a class such as a `Book` class or a `Student` class that you could then make individual objects with. For the changes: Think of a class that you would find in a furniture store. Follow the instructions from the assessment to give that class 4 attributes with data types and 4 methods in which you describe how the methods alter an attribute or attributes. The attributes and method portion of your two examples were solid, so no need to stray from the structure you already have in place. Then, create a specific example object of the class you chose and fill in the values for the attributes and methods. Name these two files the with the same structure you had before as `class_3.txt` and `class_3_example_object.txt`. You can commit these two files together. Once you've made the updates then send us a link to your mod_0_skills repo, so we can take a look. If you have any questions about the instructions or my feedback then please reach out so we can clarify. Once you've made the updates we will update your status. Thanks Nancy!

### Assessment Results
- [ ] Technical Ready
- [x] Pending
- [ ] Not Technical Ready

**Comment by nancylee713** [comment]
Thanks for the detailed feedback! I will send a link to Slack
